### ISSUE TITLE
Performance with Write

### ISSUE THREAD

**Issue by testcheyi** [hirochachacha/go-smb2#4]
I noticed that file upload using go-smb2 takes twice the time it takes using windows copy on to a remote smb based share.
Looking at the wireshark, i noticed a difference in that every write is preceded  and succeeded by seek. Could some one explain why it needs to do pre and post seek for every write.

https://github.com/hirochachacha/go-smb2/blob/30644f363873425d225f18578603c2f4e51845e1/client.go#L1120

**Comment by hirochachacha** [comment]
`off, err := f.seek(0, os.SEEk_CUR)` is used for getting current seek position. It's not so problematic. Maybe, the problem is the implementation of `seek` itself. Current implementation always try to fetch file position from remote server, however I guess that file position should not be global, different file handles should maintain different file positions apiece. I'll change the code later, Thanks.
