### ISSUE TITLE
Can it command execution? It seems that we can only use the file operation.

### ISSUE THREAD

**Issue by shadow1ng** [hirochachacha/go-smb2#47]
Can it command execution? It seems that we can only use the file operation.

**Comment by hirochachacha** [comment]
What does command execution mean? MSRPC? You can implement these protocols on top of this library.
e.g. https://github.com/hirochachacha/go-smb2/blob/master/client.go#L118

**Comment by shadow1ng** [comment]
like smbexec

**Comment by shadow1ng** [comment]
https://github.com/SecureAuthCorp/impacket/blob/master/examples/smbexec.py  
use password or ntml to run cmd  
![image](https://user-images.githubusercontent.com/39651966/118745062-08584e00-b888-11eb-8504-1af30941a3fc.png)
![image](https://user-images.githubusercontent.com/39651966/118745088-14dca680-b888-11eb-94b0-774961a748a3.png)

**Comment by hirochachacha** [comment]
I see. it's a part of MSRPC.

https://github.com/hirochachacha/go-smb2/blob/master/client.go#L129
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-scmr/e7a38186-cde2-40ad-90c7-650822bd6333

You should open `svcctl` instead of `srvsvc`, then need to do some works.

Supporting MSRPC protocols are too broad topic to be implemented in this library. So I'll close this issue.
